# Generated by Django 3.2.12 on 2022-03-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_visit", "0002_add_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Used for storing ad hoc / ephemeral data - e.g. GeoIP.",
            ),
        ),
    ]
