# Generated by Django 3.0.8 on 2020-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_visit', '0002_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The time to update the record in the database (!=timestamp)'),
        ),
    ]
