# Generated by Django 4.2.6 on 2023-10-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_visit", "0003_uservisit_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="browser",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="device",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="uservisit",
            name="os",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
