name: Python / Django

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [fmt, lint, mypy]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python (3.12)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install and run tox
        run: |
          pip install tox
          tox

  checks:
    name: Run Django tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: ["django-checks"]
    env:
      TOXENV: ${{ matrix.toxenv }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python (3.12)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install and run tox
        run: |
          pip install tox
          tox

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12", "3.13"]
        django: ["52", "60", "main"]

    env:
      TOXENV: django${{ matrix.django }}-py${{ matrix.python }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install and run tox
        run: |
          pip install tox
          tox
